<style>
    label{
        display: block;
    }
    hgroup {
        margin: 0 auto;
        width: 50%;
        text-align: center;
    }
    h1, h2, h3, h4{
        font-weight: bold;
    }
</style>
<section class="main-content">
    <div class="container">
        <div style="width: 95%; margin: 0 auto;">
            <hgroup>
                <h3>ENTREVISTA A PROFUNDIDAD</h3>
                <h4>GUIA PARA EL ENTREVISTADOR  DE CADENAS PRODUCTIVAS</h4>
                <h4>SELECCION DE PERSONAS REGISTRADAS EN EL CENSO 2014 Y CLASIFICADA SEGÚN TIPOLOGÍA</h4>
            </hgroup>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">
                        A. IDENTIFICACIÓN Y PREPARACIÓN DE LA ENTREVISTA 
                    </h3>
                    <label>
                        Las preguntas 1 a 12 son diligenciadas por el entrevistador de acuerdo a los datos tomados del registro censal realizado en el 2014 y del documento de identidad del entrevistado
                    </label>
                </div>
                <div class="panel-body">
                    <label id='preguntano1'>1. Número de formulario seleccionado:</label><br/>
                    <label id='preguntano0'><span style="font-size: 1.5em;" class="label label-info"><?php echo $id; ?></span></label><br/>
                    <label>2. Departamento y municipio actual de residencia (A3 Registro Censo 2014):</label>
                    <label id='preguntano0'>Departamento:</label><br/>
                    <select class="form-control">
                        <option>Seleccione Departamento...</option>
                    </select>
                    <br/>
                    <label>Municipio:</label><br/>
                    <select class="form-control">
                        <option>Seleccione Municipio...</option>
                    </select>
                    <br/>
                    <legend></legend>
                    <label id='preguntano3'>3. Dirección (A4 Censo 2014):</label><br/>
                    <textarea class="form-control"></textarea><br/>
                    <legend></legend>
                    <label id='preguntano4'>4. Zona:</label><br/>
                    <input type='text' class="form-control"><br/>  
                    <legend></legend>
                    <label id='preguntano5'>5. Nombres del entrevistado (como aparece en el formulario de registro del Censo 2014):</label><br/>
                    <input type='text' class="form-control"><br/>
                    <legend></legend>
                    <label id='preguntano6'>6. Apellidos del entrevistado (como aparece en el formulario de registro del Censo 2014):</label><br/>
                    <input type='text' class="form-control"><br/>            
                    <legend></legend>
                    <label id='preguntano7'>7. Edad actual del entrevistado (calcule la edad de acuerdo a la casilla A11 del registro del Censo 2014):</label><br/>
                    <input type='text' class="form-control"><br/>
                    <legend></legend>
                    <label id='preguntano8'>8. ¿Existe cambio en el municipio de residencia entre el 2008 y la actualidad? (verifique con casillas A3 y B1 del registro)</label><br/>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-primary active">
                            <input type="radio" name="pregunta8" value="1"> Si
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="pregunta8" value="2"> No
                        </label>
                    </div>
                    <br/>
                    <br/>
                    <legend></legend>
                    <label id='preguntano9'>9. Actividad económica del entrevistado en el 2008 (Código registrado en la casilla B7 del registro del censo 2014).</label><br/>
                    <input type='text' class="form-control"><br/>
                    <legend></legend>
                    <label id='preguntano1'>10. ¿A qué cadena productiva se integra esta actividad económica?</label><br/>
                    <label id='preguntano0'> Código de cadena productiva</label><br/>
                    <input type='text' class="form-control"><br/>            
                    <label id='preguntano0'> ¿Otro Cual?</label><br/>
                    <input type='text' class="form-control"><br/>
                    <legend></legend>
                    <label id='preguntano1'>11. ¿En el proceso de registro el entrevistado autorizó el habeas data? (el cual se mantiene hasta el momento)</label><br/>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-primary active">
                            <input type="radio" name="pregunta11" value="1"> Si
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="pregunta11" value="2"> No
                        </label>
                    </div>
                    <br/>
                    <br/>
                    <legend></legend>
                    <label id='preguntano1'>12. Números de teléfono registrados (casilla A6 del Censo 2014):</label><br/>
                    <label>Telefono 1</label>
                    <input type='text' class="form-control"><br/>
                    <label>Telefono 2</label>
                    <input type='text' class="form-control"><br/>
                    <legend></legend>
                    <label id='preguntano1'>13. Fecha de la comunicación por parte de EMGESA de la realización de la entrevista:</label><br/>
                    <input type='date' class="form-control"><br/>
                    <label id='preguntano1'>14. ¿Se pudo realizar la entrevista?</label><br/>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-primary active">
                            <input type="radio" name="pregunta11" value="1"> Si
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="pregunta11" value="2"> No
                        </label>
                    </div>
                    <br/>
                    <br/>
                    <legend></legend>
                    <label id='preguntanoP'>Para el diligenciamiento de las preguntas 15 a 19 solicite el documento de identidad del entrevistado 0</label><br/>
                    <textarea class="form-control"></textarea><br/>
                    <label id='preguntano1'>15. Tipo de documento:</label><br/>
                    <select class="form-control">
                        <option>Seleccione Tipo de documento...</option>
                    </select>
                    <label id='preguntano1'>16. Número de documento:</label><br/>
                    <input type='text' class="form-control"><br/>
                    <label id='preguntano1'>17. ¿El tipo y número de documento de identidad coincide con el registrado en el censo 2014?</label><br/>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-primary active">
                            <input type="radio" name="pregunta11" value="1"> Si
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="pregunta11" value="2"> No
                        </label>
                    </div>
                    <br/>
                    <br/>
                    <legend></legend>
                    <label id='preguntano1'>18. Lugar de expedición:</label><br/>
                    <input type='text' class="form-control"><br/>
                    <label id='preguntano0'>Departamento:</label><br/>
                    <select class="form-control">
                        <option>Seleccione Departamento...</option>
                    </select>
                    <br/>
                    <label id='preguntano1'>19. Fecha de expedición:</label><br/>
                    <input type='date' class="form-control"><br/>
                    <label id='preguntano2'>20. ¿Se autorizó la grabación de la entrevista?</label><br/>
                    <div class="btn-group" data-toggle="buttons">
                        <label class="btn btn-primary active">
                            <input type="radio" name="pregunta11" value="1"> Si
                        </label>
                        <label class="btn btn-primary">
                            <input type="radio" name="pregunta11" value="2"> No
                        </label>
                    </div>
                    <br/>
                    <br/>
                    <legend></legend>
                </div>
            </div>
            <label id='preguntanoB'>B. DATOS GENERALES DEL ENTREVISTADO</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>21. ¿Hay cambio de residencia? (diligencie de acuerdo a la pregunta 8)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>22. ¿Cuál fue la principal razón por la que cambió de residencia?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>23. Si pudiera, ¿volvería al lugar en donde residía en el 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>24. ¿Considera que el PHEQ tuvo que ver con su decisión de cambiar su residencia?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>25. ¿Cuántas personas hacían parte de su hogar en agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>26. ¿ Tiene el recibo de pago de energía eléctrica solicitado?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>27. Del recibo solicitado diligencie la siguiente información: (estos datos deben tomarse del recibo físico)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 a.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 b.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 c.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 d.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 e.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>28. ¿Cuál es su nivel educativo y el último año aprobado en ese nivel?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Nivel educativo:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Ninguno</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Preescolar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Primaria</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Secundaria</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Media</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Técnico profesional</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tegnológico</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Universitario</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Especialización</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Maestría</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Doctorado</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano2'>29. ¿Cuál es el nombre de la institución en la que cursó el último año aprobado?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 a.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 b.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>30. ¿Entre el 2008 y el presente ha recibido algún tipo de curso o formación para el trabajo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>31. ¿Quién o quienes le han brindado estos cursos o formación? (puede seleccionar más de una opción)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 a.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 b.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 c.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoB'>B. DATOS GENERALES DEL ENTREVISTADO (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>32. ¿Desea usted recibir formación para fortalecer sus capacidades y obtener un mejor trabajo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>33. ¿En qué área le interesaría recibir esta formación?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>34. ¿A qué actividad dedicaba usted la mayor parte del tiempo en agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Trabajar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Buscar trabajo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Oficios del hogar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Estudiar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Otra actividad, ¿cuál? _____________________________________</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Estaba incapacitado permanentemente para trabajar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>35. Además de realizar esta actividad, ¿Tenía un negocio o trabajo por el que recibía ingresos en agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>36. ¿Qué hacía en ese trabajo o actividad? (sea lo más detallado posible)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>37. ¿Con que frecuencia realizó este trabajo durante el mes de agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Todas las semanas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Algunas semanas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 De vez en cuando</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>38. ¿Cuántas horas a la semana dedicaba a este trabajo en agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Horas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano3'>39. Desde enero hasta agosto de 2008, ¿durante cuántos meses realizó este trabajó?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Número de meses</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>40. ¿Cuál era el nombre de la empresa, negocio, finca o persona donde trabajaba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>41. ¿En dónde estaba ubicada esa empresa,negocio,finca o persona donde usted trabajaba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Departamento</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Barrio o vereda:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>42. ¿A qué actividad se dedicaba principalmente la empresa, negocio, finca o persona  donde usted trabajaba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>43. ¿Usted era el propietario de la empresa, negocio o finca?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoE'>Entrevistador: Revise la documentación entregada por el entrevistado en el momento de  su inscripción en el Censo y verifique que la informacion reportada en materia de actividad laboral, nombre de empresa, finca, negocio o persona para quien laboraba coincida  0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>44.   ¿La información reportada en la preguntas anteriores coincide con lo reportado por las certificaciones entregadas en el proceso de inscripción del censo 2014?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoE'>Entrevistador: De acuerdo a la narración de las preguntas 36, 40, 41, 42 y 43, así como de la información que el entrevistado haya adjuntado con anterioridad a la entrevista diligencie el cuadro que aparece a continuación 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Posición ocupacional</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 1. Obrero o empleado de empresa particular</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 2. Trabajador o ayudante sin remuneración</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 3. Jornalero o peón</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 4. Trabajador por cuenta propia</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 5. Patrón o empleador</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 6. Otro, ¿cuál?_________________________</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>45. ¿Para realizar ese trabajo tenía algún tipo de contrato?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>46. Antes de descuentos (Salud, pensión u otros descuentos de nómina), ¿Cuánto ganó usted el mes de agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 (Excluya pagos en especie)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>47. Además del salario en dinero en agosto de 2008, ¿usted recibía como parte de pago de su trabajo:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 a.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 b.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 c.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>48. Además del salario en dinero, en agosto de 2008, ¿usted recibía una parte del producto como parte de pago de su trabajo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano4'>49. ¿La empresa, negocio o persona que le contrataba fue reubicada por la ejecución del PHEQ?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>50. ¿Sabe usted, dónde se ubica actualmente dicha empresa negocio o persona?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a pregunta 107 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            "<label id='preguntanoE'>Entrevistador: De acuerdo a la clasificación hecha en  el cuadro de cruce entre posición ocupacional y cadena productiva que se encuentra antes de la pregunta 45,  proceda de la siguiente manera:
                Si la cadena es código 1 a 5,  y la posición ocupacional 4 o 5 continúe con la pregunta 51, relacionada con actividades agricolas
                Si la cadena es código 6, y la posición ocupacional 4 o 5,  pase a la pregunta 60 relacionada con sector forestal
                Si la cadena es código 7, y la posición ocupacional 4 o 5, pase a la pregunta 67, sobre actividades pecuarias
                Si la cadena es código 8, y la posición ocupacional 4 o 5, pase a la pregunta 73 relacionada con actividades de pesca
                Si la cadena es código 9, y la posición ocupacional 4 o 5, pase a la pregunta 81, relacionada con actividades mineras o extractivas
                Si la cadena es código 10, y la posición ocupacional 4 o 5, pase a pregunta 87, relacionada con actividades de transporte de  mercancías o insumos                                                                                                                                                                                                                                                       Si la cadena es código 11, y la posición ocupacional 4 o 5, pase a pregunta 92, relacionadas con actividades de transporte de pasajeros
                Si la cadena es código 12, y la posición ocupacional 4 o 5, pase a la pregunta 97, relacionada con actividades comerciales
                Si la cadena es código 13, pase a la pregunta 104 0</label><br/>"
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>51. En la finca donde usted trabajaba ¿Cuál era el área destinada para ese cultivo en el 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Área</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>52. ¿Hacía rotación de ese cultivo con otro tipo de cultivos?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>52A. ¿Asociaba ese cultivo con otro tipo de cultivos?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>53. ¿Las labores de siembra, mantenimiento y cosecha del cultivo las realizaba sólo o con otras personas?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Solo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Con otras personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>54. Cuántas personas pagadas y no pagadas le ayudaban en ese cultivo y que labores desarrollaban?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Etapa</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Siembra</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Mantenimiento</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Cosecha</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>55. ¿Qué tipo de abonos o fertilizantes utilizaba para este cultivo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Abonos o fertilizantes </label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>56. ¿Dónde adquiría los abonos o  fertilizantes que utilizaba para este cultivo? (Nombre, dirección y telefono del proveedor si los compraba)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 N/A</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Abonos o Fertilizantes</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>57. ¿Qué porcentaje de la producción vendía y a quien lo hacía?  (Nombre, dirección y telefono del comprador)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 %</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>58. ¿De qué manera transportaba su producción al sitio de venta?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo propio</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo contratado</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No la transportaba</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano5'>59. ¿Qué tipo de semillas utilizaba y cómo las obtenía?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de semillas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>60. ¿Cuál era el área destinada para la producción forestal en el 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Área</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>61. ¿Qué especies de árboles tenía plantados, cuántos árboles por especie tenía y que área ocupaban en el 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Especie</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>62. ¿Las labores de siembra, mantenimiento o tala las realizaba sólo o con otras personas?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Solo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Con otras personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>63. ¿Cuántas personas pagadas y no pagadas le ayudaban y  qué labores realizaban?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Etapa</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Siembra</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Mantenimiento</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tala</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>64. ¿Qué cantidad de su producción vendía, con qué periodicidad y a quién lo hacía?  (Nombre, dirección y telefono del comprador)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 %</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>65. ¿De qué manera transportaba su producción?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo propio</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo contratado</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No la transportaba</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>65A. ¿Qué tipo de semillas utilizaba y cómo las obtenía?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de semillas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>66. ¿Tenía permiso para realizar la explotación forestal?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Si</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>67. En Agosto de 2008, ¿Qué que razas de ganado vacuno tenía, cuántos animales tenía por raza y cuál era el uso que les daba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Razas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>68. ¿Elaboraba productos derivados como queso, quesillo o embutidos entre otros?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano6'>69. ¿Qué tipo de productos elaboraba y cuál era su producción mensual?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Productos</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>70. ¿Las labores de producción las realizaba sólo o con otras personas?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Solo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Con otras personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>71. ¿Cuántas personas pagadas y no pagadas le ayudaban y para que labores? </label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Etapa</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Cría</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Levante u ordeño</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sacrificio</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Producción de derivados</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>72. ¿Qué cantidad de su producción vendía mensualmente y a quien lo hacía?  (Nombre, dirección y telefono del comprador)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Producto</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>72A. ¿De qué manera transportaba su producción?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo propio</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo contratado</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No la transportaba</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>72B. ¿Dónde adquiría los insumos (terneros, vacunas, insumos para la producción de derivados entre otros) que utilizaba para la producción pecuaria? (Nombre, dirección y telefono del proveedor si los compraba)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 N/A</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de insumo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>73. ¿En qué sitios pescaba usted en agosto del 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>74. ¿Qué cantidad de pescado y que variedades extraía usted a la semana?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Variedad</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>75. ¿En qué mes o meses del año era su mayor pesca y cuántas unidades extraía?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Mes del año</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>76. ¿Qué técnica de pesca utilizaba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>77. ¿Pescaba con  embarcación?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>78. ¿Podría suministrarme los datos de la persona dueña de la embarcación?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de embarcación:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Nombre de la persona de contacto:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Teléfonos:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano7'>79. ¿Qué cantidad de su producción vendía al día y a quién lo hacía?  (Nombre, dirección y teléfono del comprador si era mayorista)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Cantidad</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>80. ¿Tenía permiso para realizar esta actividad?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Si</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>81. ¿En qué lugar o lugares realizaba esta actividad extractiva, que tipo de material extraía, que cantidad y con qué periodicidad lo hacía?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Lugar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>82. ¿Las labores de extracción las realizaba sólo o con otras personas?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Solo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Con otras personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>83. ¿Cuántas personas pagadas y no pagadas le ayudaban y para que labores? </label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Número total de personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>84. ¿De qué manera transportaba el material que extraía?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo propio</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo contratado</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No lo transportaba</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>85. En dónde y a quiénes vendía el producto de la explotación</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En dónde</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>86. ¿Tenía permiso para realizar esta actividad?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Si</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>87. Entre los meses de enero y agosto de 2008, ¿Qué rutas cubría y con qué frecuencia? (pida al entrevistado que sea lo más específico con la ubicación de los situios de inicio y finalización de cada ruta)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Rutas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>88. ¿Qué tipo de productos trasportaba y con qué tipo de vehículos lo hacía?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Clase de productos</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano8'>89. ¿El transporte de estos productos lo realizaba sólo o con otras personas?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Solo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Con otras personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>90. ¿Cuántas personas pagadas y no pagadas le ayudaban y para que labores?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Número total de personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>91. ¿Quiénes eran sus principales clientes en la zona de influencia del PHEQ y dónde se ubicaban?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Clientes</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>91A. ¿Dónde adquiría los insumos (Gasolina, lubricantes, repuestos entre otros) que utilizaba para realizar esta actividad? (Nombre, dirección y telefono del proveedor si los compraba)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de insumo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Entre los meses de enero y agosto de 2008, ¿Qué rutas cubría con qué frecuencia y cuántas personas por frecuencia transportaba? (pida al entrevistado que sea lo más específico con la ubicación de los sitios de inicio y finalización de cada ruta)</label><br/>
            <label id='preguntano9'>92. 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Rutas (Inicio, intermedias, fin)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoC'>C. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>93. ¿Qué tipo de vehículos utilizaba y cuál era su capacidad?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Vehículo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>94. ¿Esta actividad la  realizaba sólo o con otras personas?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Solo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Con otras personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>95. ¿Cuántas personas pagadas y no pagadas le ayudaban y para que labores?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Número total de personas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>96.  ¿Se encontraba afiliado o asociado a alguna empresa?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Si</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>96A. ¿Dónde adquiría los insumos (Gasolina, lubricantes, repuestos entre otros) que utilizaba para realizar esta actividad? (Nombre, dirección y telefono del proveedor si los compraba)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de insumo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 104 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>97. Durante el mes de agosto de 2008, ¿Qué productos, Qué cantidades y con que frecuencia comercializaba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de productos</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>98. ¿Comercializaba sus productos en forma estacionaria o ambulante?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Estacionaria</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Ambulante</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano9'>99. En agosto de 2008, ¿cuántos establecimientos tenía para comercializar sus productos y en donde estaban ubicados?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Nro.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 1</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 2</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 3</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 4</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 101 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoB'>B. SITUACIÓN LABORAL EN AGOSTO DE 2008 (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>100. Entre los meses de enero y agosto de 2008, ¿Qué recorrido hacía  para vender sus productos y con que frecuencia lo realizaba? (pida al entrevistado que sea lo más específico con la ubicación de los situios de inicio y finalización de cada ruta)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Recorrido</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>101. Entre los meses de enero y agosto de 2008, ¿A quién(es) le compraba los productos que comercializaba?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Tipo de producto</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>102. ¿Para comercializar sus productos utilizaba algún vehículo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>103. ¿El vehículo era de su propiedad o contratado?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo propio</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 En un vehículo contratado</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>104. ¿Cuál fue la ganancia neta por esa actividad o negocio durante el mes de agosto de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 $</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>105. ¿Cuál fue su ganancia neta por esa actividad o negocio entre los meses de septiembre de 2007 y julio de 2008?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 $</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>106. Entre enero y agosto de 2008, ¿Cuántos meses trabajo en esa empresa, negocio o finca o para esa persona?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Número de meses</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoD'>D. SITUACIÓN LABORAL ACTUAL</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>107. ¿En este momento continúa realizando  el mismo trabajo o negocio?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>108. ¿A qué actividad dedicó usted la mayor parte del tiempo la semana pasada?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Trabajar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Buscar trabajo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Oficios del hogar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Estudiar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Otra actividad, ¿cuál?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Estaba incapacitado permanentemente para trabajar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>109. Ademas de realizar esta actividad, ¿Tenía la semana pasada un negocio o trabajo por el que recibía ingresos?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>110. ¿Qué hace en ese trabajo? (sea lo más detallado posible)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoD'>D. SITUACIÓN LABORAL ACTUAL (continuación)</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>111. ¿Con que frecuencia realizó este trabajo el mes pasado?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 El mes completo</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Menos del mes</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>112. ¿Cuántas horas a la semana trabaja normalmente?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Horas</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>113. ¿Desde hace cuántos meses realiza este trabajo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Número de meses</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>114. ¿Cuál es el nombre de la empresa, negocio,  finca o persona donde o para la cual trabaja?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>115. ¿En dónde está ubicado esa empresa, negocio o finca donde trabaja?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Departamento</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Barrio o vereda:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>116. ¿A que actividad se dedica principalmente la empresa o negocio en la que usted realiza su trabajo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>117. En este trabajo usted es:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Obrero o empleado de empresa particular</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Obrero o empleado del gobierno</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Empleado doméstico</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Jornalero o peón</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Trabajador po cuenta propia</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Patrón o empleador</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Trabajador sin remuneración</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>118. Antes de descuentos, ¿Cuánto ganó usted el mes pasado en este empleo?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 $</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>119. ¿Para realizar este trabajo tiene algún tipo de contrato?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Sí.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoP'>Pase a la pregunta 121 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>120. ¿Cuál fue la ganacia neta por esa actividad o negocio durante el mes pasado?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 $</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>121. ¿Entre septiembre de 2008 y la actualidad, qué ha cambiado en su situación laboral?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>122. ¿Por qué considera que el PHEQ ha afectado su situación laboral?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoE'>E. CONSIDERACIONES GENERALES DEL ENTREVISTADO SOBRE LA COMPENSACIÓN Y LA INSCRIPCIÓN</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>123. En sus palabras, ¿qué es una compensación, cuándo se aplica y quienes tienen derecho a recibirla?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>124. ¿Por qué cuándo el proyecto hizo censos en el 2008 y 2009, usted no fue incluído?</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoF'>F. OBSERVACIONES DEL ENTREVISTADOR</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>125. Apreciación del entevistador sobre la consistencia de las respuestas:</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>126. Observaciones sobre la afectación en el desarrollo de su trabajo entre 2008 y la actualidad</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>127. Otras observaciones</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoG'>G. CONTROL DE LA ENTREVISTA</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>128. Fecha de aplicación de la entrevista</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>129. Nombre del entrevistador</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 CC.</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano1'>130. Resultado final de la entrevista</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Competa</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 Incompleta</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntano0'>0 No se pudo realizar</label><br/>
            <textarea class="form-control"></textarea><br/>
            <label id='preguntanoF'>Firma del entrevistado 0</label><br/>
            <textarea class="form-control"></textarea><br/>
            <textarea class="form-control"></textarea><br/>
        </div>
    </div>
</section>